/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameapp;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author x17124719
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Lbl = new javax.swing.JLabel();
        player2Lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionTa = new javax.swing.JTextArea();
        square15Lbl = new javax.swing.JLabel();
        square16Lbl = new javax.swing.JLabel();
        square1Lbl = new javax.swing.JLabel();
        square2Lbl = new javax.swing.JLabel();
        square3Lbl = new javax.swing.JLabel();
        square4Lbl = new javax.swing.JLabel();
        square5Lbl = new javax.swing.JLabel();
        square6Lbl = new javax.swing.JLabel();
        square7Lbl = new javax.swing.JLabel();
        square8Lbl = new javax.swing.JLabel();
        square9Lbl = new javax.swing.JLabel();
        square10Lbl = new javax.swing.JLabel();
        square11Lbl = new javax.swing.JLabel();
        square12Lbl = new javax.swing.JLabel();
        square13Lbl = new javax.swing.JLabel();
        square14Lbl = new javax.swing.JLabel();
        square17Lbl = new javax.swing.JLabel();
        square18Lbl = new javax.swing.JLabel();
        rollBtn = new javax.swing.JButton();
        diceLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1Lbl.setText("Player1");

        player2Lbl.setText("Player2");

        questionTa.setColumns(20);
        questionTa.setRows(5);
        jScrollPane2.setViewportView(questionTa);

        square15Lbl.setText("Square15");

        square16Lbl.setText("Square16");

        square1Lbl.setText("Square1");

        square2Lbl.setText("Square2");

        square3Lbl.setText("Square3");

        square4Lbl.setText("Square4");

        square5Lbl.setText("Square5");

        square6Lbl.setText("Square6");

        square7Lbl.setText("Square7");

        square8Lbl.setText("Square8");

        square9Lbl.setText("Square9");

        square10Lbl.setText("Square10");

        square11Lbl.setText("Square11");

        square12Lbl.setText("Square12");

        square13Lbl.setText("Square13");

        square14Lbl.setText("Square14");

        square17Lbl.setText("Square17");

        square18Lbl.setText("Square18");

        rollBtn.setText("Roll");
        rollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollBtnActionPerformed(evt);
            }
        });

        diceLbl.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(square9Lbl))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(square7Lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(square8Lbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addComponent(square6Lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(player1Lbl)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(square10Lbl)
                                .addGap(43, 43, 43)
                                .addComponent(square11Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(square12Lbl)
                                .addGap(45, 45, 45)
                                .addComponent(square13Lbl)
                                .addGap(48, 48, 48)
                                .addComponent(square14Lbl)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(diceLbl)
                                        .addGap(77, 77, 77)
                                        .addComponent(rollBtn)
                                        .addGap(214, 214, 214)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(square16Lbl)
                                    .addComponent(square15Lbl)
                                    .addComponent(square17Lbl)
                                    .addComponent(square18Lbl))
                                .addGap(0, 6, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2Lbl)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(square5Lbl)
                .addGap(62, 62, 62)
                .addComponent(square4Lbl)
                .addGap(76, 76, 76)
                .addComponent(square3Lbl)
                .addGap(63, 63, 63)
                .addComponent(square2Lbl)
                .addGap(54, 54, 54)
                .addComponent(square1Lbl)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Lbl)
                    .addComponent(player2Lbl))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(square14Lbl)
                    .addComponent(square13Lbl)
                    .addComponent(square12Lbl)
                    .addComponent(square11Lbl)
                    .addComponent(square10Lbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(square9Lbl)
                                .addGap(46, 46, 46)
                                .addComponent(square8Lbl)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(square15Lbl)
                                .addGap(48, 48, 48)
                                .addComponent(square16Lbl)))
                        .addGap(41, 41, 41)
                        .addComponent(square7Lbl)
                        .addGap(54, 54, 54)
                        .addComponent(square6Lbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(square17Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(square18Lbl)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollBtn)
                            .addComponent(diceLbl))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(square1Lbl)
                    .addComponent(square2Lbl)
                    .addComponent(square3Lbl)
                    .addComponent(square4Lbl)
                    .addComponent(square5Lbl))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollBtnActionPerformed
        // TODO add your handling code here:
        Random rd=new Random();
        int number1;
        int number2;
        
        
        
        number1 = rd.nextInt(6);
        System.out.println("Player one rolled " + number1 + "");
        number2 = rd.nextInt(6);
        System.out.println("Player two rolled " + number2 + "");
            
        if(number1>number2){
            System.out.println("Player One goes first");
        }
        else if(number2>number1){
            System.out.println("Player two goes first");
        }else{
            System.out.println("Pleas roll again");
        }
                
                
        //int result=rd.nextInt(6);
        //result++;
        
             
    
        
        //JOptionPane.showMessageDialog(null, "You rolled a "+result+". Please advance to your square");
        //switch
        /*switch(result){
            case 1:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice1.png")));
                break;
            case 2:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice2.png")));
                break;
            case 3:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice3.png")));
                break;
            case 4:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice4.png")));
                break;
            case 5:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice5.png")));
                break;
            case 6:
                diceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice6.png")));
                break;
        }*/
                           
    }//GEN-LAST:event_rollBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diceLbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel player1Lbl;
    private javax.swing.JLabel player2Lbl;
    private javax.swing.JTextArea questionTa;
    private javax.swing.JButton rollBtn;
    private javax.swing.JLabel square10Lbl;
    private javax.swing.JLabel square11Lbl;
    private javax.swing.JLabel square12Lbl;
    private javax.swing.JLabel square13Lbl;
    private javax.swing.JLabel square14Lbl;
    private javax.swing.JLabel square15Lbl;
    private javax.swing.JLabel square16Lbl;
    private javax.swing.JLabel square17Lbl;
    private javax.swing.JLabel square18Lbl;
    private javax.swing.JLabel square1Lbl;
    private javax.swing.JLabel square2Lbl;
    private javax.swing.JLabel square3Lbl;
    private javax.swing.JLabel square4Lbl;
    private javax.swing.JLabel square5Lbl;
    private javax.swing.JLabel square6Lbl;
    private javax.swing.JLabel square7Lbl;
    private javax.swing.JLabel square8Lbl;
    private javax.swing.JLabel square9Lbl;
    // End of variables declaration//GEN-END:variables
}
