/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameapp;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author x17124719
 */
public class GameGUI extends javax.swing.JFrame {
    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();       
        player1=JOptionPane.showInputDialog(null,"Enter first player name");
        player1Lbl.setText(player1);
        player2=JOptionPane.showInputDialog(null,"Enter second player name");
        player2Lbl.setText(player2); 
         
        randPlayerBtn.setVisible(true);
        rollBtn.setVisible(false);
    }
    
    int player1Total = 0;
    int player2Total = 0;
    boolean playerBlueTurn;
    boolean playerRedTurn;
    boolean answerCorrect;
    ArrayList<Object> boardArray = new ArrayList<>();
    String player1;
    String player2;    

    boolean player1Turn = true;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Lbl = new javax.swing.JLabel();
        player2Lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionTa = new javax.swing.JTextArea();
        squareLbl15 = new javax.swing.JLabel();
        squareLbl16 = new javax.swing.JLabel();
        squareLbl1 = new javax.swing.JLabel();
        squareLbl2 = new javax.swing.JLabel();
        squareLbl3 = new javax.swing.JLabel();
        squareLbl4 = new javax.swing.JLabel();
        squareLbl5 = new javax.swing.JLabel();
        squareLbl6 = new javax.swing.JLabel();
        squareLbl7 = new javax.swing.JLabel();
        squareLbl8 = new javax.swing.JLabel();
        squareLbl9 = new javax.swing.JLabel();
        squareLbl10 = new javax.swing.JLabel();
        squareLbl11 = new javax.swing.JLabel();
        squareLbl12 = new javax.swing.JLabel();
        squareLbl13 = new javax.swing.JLabel();
        squareLbl14 = new javax.swing.JLabel();
        squareLbl17 = new javax.swing.JLabel();
        squareLbl18 = new javax.swing.JLabel();
        rollBtn = new javax.swing.JButton();
        randPlayerBtn = new javax.swing.JButton();
        startGameBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        player1Lbl.setText("Player1");
        getContentPane().add(player1Lbl);
        player1Lbl.setBounds(20, 20, 36, 15);

        player2Lbl.setText("Player2");
        getContentPane().add(player2Lbl);
        player2Lbl.setBounds(750, 20, 36, 15);

        questionTa.setColumns(20);
        questionTa.setRows(5);
        jScrollPane2.setViewportView(questionTa);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 130, 432, 192);

        squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        squareLbl15.setToolTipText("");
        getContentPane().add(squareLbl15);
        squareLbl15.setBounds(680, 100, 81, 61);

        squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl16);
        squareLbl16.setBounds(680, 200, 81, 61);

        squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl1);
        squareLbl1.setBounds(580, 470, 81, 61);

        squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl2);
        squareLbl2.setBounds(480, 470, 81, 61);

        squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl3);
        squareLbl3.setBounds(370, 470, 81, 61);

        squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl4);
        squareLbl4.setBounds(260, 470, 81, 61);

        squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl5);
        squareLbl5.setBounds(150, 470, 81, 61);

        squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl6);
        squareLbl6.setBounds(60, 380, 81, 61);

        squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl7);
        squareLbl7.setBounds(60, 290, 81, 61);

        squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl8);
        squareLbl8.setBounds(60, 200, 81, 61);

        squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl9);
        squareLbl9.setBounds(60, 110, 81, 61);

        squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl10);
        squareLbl10.setBounds(150, 20, 81, 61);

        squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl11);
        squareLbl11.setBounds(260, 20, 81, 61);

        squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl12);
        squareLbl12.setBounds(370, 20, 81, 61);

        squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl13);
        squareLbl13.setBounds(490, 20, 81, 61);

        squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl14);
        squareLbl14.setBounds(590, 20, 81, 61);

        squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl17);
        squareLbl17.setBounds(680, 290, 81, 61);

        squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png"))); // NOI18N
        getContentPane().add(squareLbl18);
        squareLbl18.setBounds(680, 380, 81, 61);

        rollBtn.setText("Roll");
        rollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rollBtn);
        rollBtn.setBounds(380, 410, 70, 25);

        randPlayerBtn.setText("Press To See Who Goes First");
        randPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randPlayerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(randPlayerBtn);
        randPlayerBtn.setBounds(320, 340, 210, 25);

        startGameBtn.setText("Start Game");
        startGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startGameBtn);
        startGameBtn.setBounds(370, 370, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/blue.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollBtnActionPerformed
ArrayList<String> questions = new ArrayList<String>();
        ArrayList<String> answers = new ArrayList<String>();
        
        //Adding questions to the quesiton array
        questions.add("Who was the legendary Benedictine monk who invented champagne?");
        questions.add("Name the largest freshwater lake in the world?");
        questions.add("Where would you find the Sea of Tranquility?");
        questions.add("What is someone who shoes horses called?");
        questions.add("What item of clothing was named after its Scottish inventor?");
        questions.add("What kind of weapon is a falchion?");
        questions.add("Which word goes before vest, beans and quartet?");
        questions.add("What is another word for lexicon?");
        questions.add("Name the seventh planet from the sun.");
        questions.add("Who invented the rabies vaccination?");
        questions.add("Which is the only American state to begin with the letter p?");
        questions.add("Name the world biggest island");
        questions.add("What is the worlds longest river?");
        questions.add("Name the worlds largest ocean.");
        questions.add("What is the diameter of Earth?");
        questions.add("Where would you find the worlds most ancient forest?");
        questions.add("What is the capital city of Spain?");
        questions.add("Which country is Prague in?','Czech Republic");
        questions.add("Which English town was a forerunner of the Parks Movement and the first city in Europe to have a street tram system?");
        questions.add("Name the actor who starred in 142 films including The Quiet Man, The Shootist, The Searchers and Stagecoach.");
        questions.add("Name the film noir actress who starred in I Married a Witch, The Glass Key, So Proudly We Hail! and Sullivans Travels");
        questions.add("What is the oldest film ever made?','Roundhay Garden Scene");
        questions.add("Which actress has won the most Oscars?");
        questions.add("Which actress said, 'Fasten your seatbelts. Its going to be a bumpy night' in All About Eve?");
        questions.add("Name the director of the Lord of the Rings trilogy.");
        questions.add("Who played Neo in The Matrix?");
        questions.add("Name the actress whose career began at the age of 3, and who went on to star in films such as Contact, Maverick and The Silence of the Lambs?");
        questions.add("Bray Studios, near Windsor in Berkshire, was home to which famous brand of horror films?");
        questions.add("In which film did Humphrey Bogart say, 'We will always have Paris?'");
        questions.add("By what name is Lancelot Brown more usually known?");
        questions.add("Name the world famous gardens situated ten miles outside of London, close to the River Thames.");
        questions.add("Which popular gardener created Barnsdale Gardens and was the author of many books such as The Ornamental Kitchen Garden, Gardeners World, Practical Gardening Course and Paradise Gardens?'");
        questions.add("Which garden is considered to be among the Seven Wonders of the Ancient World?");
        questions.add("What colour is a Welsh poppy?");
        questions.add("What colour is a Himalayan poppy?");
        questions.add("Name the organic gardener who is almost as famous for his long blond plait as he is for his books such as Going Organic and The Gourmet Gardener and his regular appearances on the BBC radios Gardeners Question Time.");
        questions.add("Give the alternative name for a Mountain Ash tree.");
        questions.add("Which kind of bulbs were once exchanged as a form of currency?");
        questions.add("By which Latin name was Rosa Gallica previously known?");
        questions.add("What colour jersey is worn by the winners of each stage of the Tour De France?");
        questions.add("Name the only heavyweight boxing champion to finish his career of 49 fights without ever having been defeated?");
        questions.add("Which sport does Constantino Rocca play?");
        questions.add("Name the country where you would find the Cresta Run.");
        questions.add("How many times was the Mens Tennis Singles at Wimbledon won by Bjorn Borg?");
        questions.add("In 2011, which country hosted a Formula 1 race for the first time?");
        questions.add("Name the game played on a lawn called a 'crown green'.");
        questions.add("Which chess piece can only move diagonally?");
        questions.add("Name the only footballer to have played for Liverpool, Everton, Manchester City and Manchester United.");
        questions.add("In football, who was nicknamed 'The Divine Ponytail'?");
        questions.add("How many valves does a trumpet have?");

        //Adding the Answers to the answer array
        answers.add("Dom Perignon");
        answers.add("Lake Superior");
        answers.add("The Moon");
        answers.add("A farrier");
        answers.add("A Mackintosh");
        answers.add("A sword");
        answers.add("String");
        answers.add("Dictionary");
        answers.add("Uranus");
        answers.add("Louis Pasteur");
        answers.add("Pennsylvania");
        answers.add("Greenland");
        answers.add("'Amazon");
        answers.add("'Pacific");
        answers.add("8000 miles");
        answers.add("Australia");
        answers.add("Madrid");
        answers.add("Czech Republic");
        answers.add("Birkenhead");
        answers.add("John Wayne");
        answers.add("Veronica Lake");
        answers.add("Roundhay Garden Scene");
        answers.add("Katharine Hepburn");
        answers.add("Bette Davis");
        answers.add("Peter Jackson");
        answers.add("Keanu Reeves");
        answers.add("Jodie Foster");
        answers.add("Hammer Horror");
        answers.add("Casablanca");
        answers.add("Capability Brown");
        answers.add("Kew Gardens");
        answers.add("Geoff Hamilton");
        answers.add("The Hanging Gardens of Babylon");
        answers.add("Yellow'");
        answers.add("Blue");
        answers.add("Bob Flowerdew");
        answers.add("Rowan");
        answers.add("Tulips");
        answers.add("Rosa Mundi");
        answers.add("Yellow");
        answers.add("Rocky Marciano");
        answers.add("Golf");
        answers.add("Switzerland");
        answers.add("Five");
        answers.add("India");
        answers.add("Bowls");
        answers.add("A bishop");
        answers.add("Peter Beardsley");
        answers.add("Roberto Baggio");
        answers.add("Three");

        String answer;
        //Loop to get question and take answer
        for (int i = 0; i < 1; i++) {
            Random rd=new Random();
            int qNum=rd.nextInt(questions.size())+1;            
            for (int j = 0; j < 1; j++) {
                questionTa.append(questions.get(qNum) + "\n");
                System.out.println(answers.get(qNum));
                answer = JOptionPane.showInputDialog(null, "");                
                if (answer.contains(answers.get(qNum))) {
                    JOptionPane.showMessageDialog(null, "Right Answer");
                    answerCorrect = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong answer");
                    answerCorrect = false;
                }
            }
        }    
      
      //Runs if the answer is correct
      if(answerCorrect){ 
          //Player 1 game loop
        if(player1Turn){
            Random rd=new Random();
            int result=rd.nextInt(6)+1;            
            JOptionPane.showMessageDialog(null, "Player 1 rolled a "+result+". Please advance to your square");
            
            //Switch statement to remove previous game piece
            switch(player1Total){
                case 1 : if(player1Total == player2Total){
                squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 2: if(player1Total == player2Total){
                squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 3: if(player1Total == player2Total){
                squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 4: if(player1Total == player2Total){
                squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 5: if(player1Total == player2Total){
                squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 6: if(player1Total == player2Total){
                squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 7: if(player1Total == player2Total){
                squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 8: if(player1Total == player2Total){
                squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 9: if(player1Total == player2Total){
                squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 10: if(player1Total == player2Total){
                squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 11: if(player1Total == player2Total){
                squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 12: if(player1Total == player2Total){
                squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 13: if(player1Total == player2Total){
                squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 14: if(player1Total == player2Total){
                squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 15: if(player1Total == player2Total){
                squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 16: if(player1Total == player2Total){
                squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 17: if(player1Total == player2Total){
                squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 18: if(player1Total == player2Total){
                squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                else{
                    squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
            }
            System.out.println("Player 1 old: " + player1Total);
            player1Total += result;
            if(player1Total >= 18){
                player1Total = 18;
                JOptionPane.showMessageDialog(null,"Congratulations. Player 1 is the winner!");
                System.exit(0);
            }
            System.out.println("Player 1 new: " + player1Total);
            
            //Updates game board with new location for game piece for player 1
            switch(player1Total){
                case 1 : if(player1Total == player2Total){
                squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 2: if(player1Total == player2Total){
                squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 3: if(player1Total == player2Total){
                squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 4: if(player1Total == player2Total){
                squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 5: if(player1Total == player2Total){
                squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 6: if(player1Total == player2Total){
                squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 7: if(player1Total == player2Total){
                squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 8: if(player1Total == player2Total){
                squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 9: if(player1Total == player2Total){
                squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 10: if(player1Total == player2Total){
                squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 11: if(player1Total == player2Total){
                squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 12: if(player1Total == player2Total){
                squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 13: if(player1Total == player2Total){
                squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 14: if(player1Total == player2Total){
                squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 15: if(player1Total == player2Total){
                squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 16: if(player1Total == player2Total){
                squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 17: if(player1Total == player2Total){
                squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
                
                case 18: if(player1Total == player2Total){
                squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                break;
            }
            
            player1Turn = false;
        }
        else{
            Random rd=new Random();
            int result=rd.nextInt(6)+1;            
            JOptionPane.showMessageDialog(null, "Player 2 rolled a "+result+". Please advance to your square");
            
            //Removes old location for player 2
            switch(player2Total){
                case 1 : if(player1Total == player2Total){
                squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 2: if(player1Total == player2Total){
                squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 3: if(player1Total == player2Total){
                squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 4: if(player1Total == player2Total){
                squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 5: if(player1Total == player2Total){
                squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 6: if(player1Total == player2Total){
                squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 7: if(player1Total == player2Total){
                squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 8: if(player1Total == player2Total){
                squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 9: if(player1Total == player2Total){
                squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 10: if(player1Total == player2Total){
                squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 11: if(player1Total == player2Total){
                squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 12: if(player1Total == player2Total){
                squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 13: if(player1Total == player2Total){
                squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 14: if(player1Total == player2Total){
                squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 15: if(player1Total == player2Total){
                squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 16: if(player1Total == player2Total){
                squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 17: if(player1Total == player2Total){
                squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
                
                case 18: if(player1Total == player2Total){
                squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareRedToken.png")));
                }
                else{
                    squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareEmpty (2).png")));
                }
                break;
            }
            System.out.println("Player 2 old: " + player2Total);
            player2Total += result;
            if(player2Total >= 18){
                player2Total = 18;
                JOptionPane.showMessageDialog(null,"Congratulations. Player 2 is the winner!");
                System.exit(0);
            }
            System.out.println("Player 2 new: " + player2Total);
            
            //Update player2 to new location
            switch(player2Total){
                case 1 : if(player1Total == player2Total){
                squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 2: if(player1Total == player2Total){
                squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 3: if(player1Total == player2Total){
                squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 4: if(player1Total == player2Total){
                squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 5: if(player1Total == player2Total){
                squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 6: if(player1Total == player2Total){
                squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 7: if(player1Total == player2Total){
                squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 8: if(player1Total == player2Total){
                squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 9: if(player1Total == player2Total){
                squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 10: if(player1Total == player2Total){
                squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 11: if(player1Total == player2Total){
                squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 12: if(player1Total == player2Total){
                squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 13: if(player1Total == player2Total){
                squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 14: if(player1Total == player2Total){
                squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 15: if(player1Total == player2Total){
                squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 16: if(player1Total == player2Total){
                squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 17: if(player1Total == player2Total){
                squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
                
                case 18: if(player1Total == player2Total){
                squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBothTokens.png")));
                }
                else{
                    squareLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameapp/images/GameSquareBlueToken.png")));
                }
                break;
            }
            player1Turn = true;
        }  
       }                                   
    }//GEN-LAST:event_rollBtnActionPerformed

    private void randPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randPlayerBtnActionPerformed
        // TODO add your handling code here:
        String names[] = {player1Lbl.getText(), player2Lbl.getText()};
        JOptionPane.showMessageDialog(null, names[new Random().nextInt(names.length)]+ " will be player 1. Please press button below to begin");
    }//GEN-LAST:event_randPlayerBtnActionPerformed

    private void startGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameBtnActionPerformed
        // TODO add your handling code here:
        randPlayerBtn.setVisible(false);
        startGameBtn.setVisible(false);
        rollBtn.setVisible(true);
    }//GEN-LAST:event_startGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel player1Lbl;
    private javax.swing.JLabel player2Lbl;
    private javax.swing.JTextArea questionTa;
    private javax.swing.JButton randPlayerBtn;
    private javax.swing.JButton rollBtn;
    private javax.swing.JLabel squareLbl1;
    private javax.swing.JLabel squareLbl10;
    private javax.swing.JLabel squareLbl11;
    private javax.swing.JLabel squareLbl12;
    private javax.swing.JLabel squareLbl13;
    private javax.swing.JLabel squareLbl14;
    private javax.swing.JLabel squareLbl15;
    private javax.swing.JLabel squareLbl16;
    private javax.swing.JLabel squareLbl17;
    private javax.swing.JLabel squareLbl18;
    private javax.swing.JLabel squareLbl2;
    private javax.swing.JLabel squareLbl3;
    private javax.swing.JLabel squareLbl4;
    private javax.swing.JLabel squareLbl5;
    private javax.swing.JLabel squareLbl6;
    private javax.swing.JLabel squareLbl7;
    private javax.swing.JLabel squareLbl8;
    private javax.swing.JLabel squareLbl9;
    private javax.swing.JRadioButton startGameBtn;
    // End of variables declaration//GEN-END:variables
}
